// =============================================================================
// CSS GENERATOR
// -----------------------------------------------------------------------------
// Turns a list of GeneratedRule objects into a final CSS string. Rules are
// grouped by breakpoint so we can emit each media query block exactly once.
// =============================================================================

import type { Breakpoint, GeneratedRule, ResolvedConfig } from "./types.js"

/** CSS-escape a selector character. Class names in this toolkit only use
 *  ASCII letters, digits and `-`, but we keep the escape minimal anyway. */
function escapeSelector(name: string): string {
  // Selectors generated by this toolkit are safe; passthrough is fine.
  return name
}

/** Serialise a single rule block to a CSS string. */
function emitRule(rule: GeneratedRule, indent: string): string {
  const sel = `.${escapeSelector(rule.selector)}`
  const body: string[] = []
  for (const [prop, value] of Object.entries(rule.decls)) {
    const v = rule.important ? `${value} !important` : value
    body.push(`${indent}  ${prop}: ${v};`)
  }
  return `${indent}${sel} {\n${body.join("\n")}\n${indent}}`
}

function stableSort(rules: GeneratedRule[]): GeneratedRule[] {
  // Sort by (category, priority, selector) to make output deterministic
  // and group related utilities together.
  return [...rules].sort((a, b) => {
    if (a.category !== b.category) return a.category - b.category
    if (a.priority !== b.priority) return a.priority - b.priority
    return a.selector.localeCompare(b.selector)
  })
}

/**
 * Build the final CSS string. The `prelude` argument is prepended verbatim
 * (used for preflight and keyframes).
 */
export function generateCss(
  rules: GeneratedRule[],
  config: ResolvedConfig,
  prelude: string,
): string {
  const byBreakpoint: Record<Breakpoint, GeneratedRule[]> = {
    base: [],
    mobile: [],
    tablet: [],
  }
  for (const r of rules) byBreakpoint[r.breakpoint].push(r)

  const out: string[] = []
  if (prelude) out.push(prelude)

  // Base utilities (no media query wrapper)
  if (byBreakpoint.base.length > 0) {
    out.push("/* @sasskit base utilities */")
    for (const r of stableSort(byBreakpoint.base)) out.push(emitRule(r, ""))
  }

  // Tablet first, mobile last so the smaller-viewport rule wins on cascade.
  // Mirrors the SASS source: `-t` is `max-width: tablet`, `-m` is
  // `max-width: mobile`. We use the same exclusive ranges as the SASS mixin.
  if (byBreakpoint.tablet.length > 0) {
    out.push(`@media (min-width: ${config.mobile + 1}px) and (max-width: ${config.tablet}px) {`)
    for (const r of stableSort(byBreakpoint.tablet)) out.push(emitRule(r, "  "))
    out.push("}")
  }
  if (byBreakpoint.mobile.length > 0) {
    out.push(`@media (max-width: ${config.mobile}px) {`)
    for (const r of stableSort(byBreakpoint.mobile)) out.push(emitRule(r, "  "))
    out.push("}")
  }

  let css = out.join("\n")
  if (!css.endsWith("\n")) css += "\n"
  if (config.minify) css = minifyCss(css)
  return css
}

/** Minimal whitespace minifier — enough to noticeably shrink output without
 *  shipping a full CSS parser. */
function minifyCss(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s*([{};:,>+~])\s*/g, "$1")
    .replace(/;}/g, "}")
    .replace(/\n+/g, "")
    .trim()
}
